"""End-to-end template: a registry-style status/age table -> a GWAS phenotype.

Mirrors the "bring your own data" flow in docs/guide.md on a small **synthetic**
table, so you have a copy-paste starting point for the plumbing. One step is
demo-only and must be swapped for real data: step 2 uses the built-in logistic
incidence (``age_thresholds``); a real analysis needs ``thresholds_from_cip`` with
your population's stratified cumulative-incidence curve (flagged inline below). The
steps are:

  1. start from one row per observed family member: fam_id, role, status, age;
  2. turn status (+age) into liability bounds with a threshold builder;
  3. group the rows into families;
  4. estimate each proband's age-aware family-history liability with Gibbs and PA;
  5. hand the estimate to a linear-regression GWAS as a quantitative phenotype.

Replace `make_toy_table()` with your own table (e.g. read a CSV into the same
columns) and set `H2` / `POP_PREV` for your disease.

Run (from the repo root): python examples/registry_pipeline.py
(installs not required — this inserts the repo root on sys.path; or `pip install -e .`.)
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ltpred import age_thresholds, families_from_columns, estimate_liability  # noqa: E402

H2 = 0.5            # liability-scale heritability (convert observed-scale first)
POP_PREV = 0.05     # population lifetime prevalence


def make_toy_table(n_fam=1500, seed=0):
    """Synthesise a registry-like long table: fam_id, role, status, age.

    Each family is a proband (`o`) plus mother, father and a sibling, with
    jointly simulated liabilities. Cases' onset ages and controls' follow-up ages
    are generated by the same logistic age-threshold model used below, so this
    demonstration is internally coherent. It still is not a production CIP."""
    from ltpred import simulate_under_LTM_single, convert_liability_to_aoo

    sim = simulate_under_LTM_single(fam_vec=["m", "f", "s1"], h2=H2, n_sim=n_fam,
                                    pop_prev=POP_PREV, use_age=True, seed=seed)
    fam_id, role, status, age = [], [], [], []
    for i, fam in enumerate(sim.families):
        for m in fam.members:
            # The simulator pins cases at their onset threshold and upper-bounds
            # controls at their follow-up threshold. Invert that same threshold
            # to recover a registry-style age column before rebuilding the bounds.
            is_case = np.isfinite(m.lower)
            threshold = m.lower if is_case else m.upper
            fam_id.append(f"fam{i}")
            role.append(m.role)
            status.append(int(is_case))
            age.append(float(convert_liability_to_aoo(threshold, pop_prev=POP_PREV)))
    return (np.array(fam_id), np.array(role), np.array(status), np.array(age),
            sim.genetic)


def main():
    fam_id, role, status, age, true_g = make_toy_table()

    # 2) status (+age) -> liability bounds.
    # DEMO ONLY: age_thresholds uses a built-in *logistic* incidence curve. That is
    # fine for this synthetic table, but NOT an acceptable real-data analysis. For
    # real registry data, replace this line with thresholds_from_cip and pass your
    # population's stratified cumulative-incidence (CIP) curve per sex / birth-year /
    # ancestry stratum, e.g.:
    #     lower, upper, K_i, K_pop = thresholds_from_cip(
    #         status, age, cip_ages, cip_values, k_pop=lifetime_prevalence)
    # See docs/data-preparation.md, "A real register-data recipe".
    lower, upper = age_thresholds(status, age, pop_prev=POP_PREV)

    # 3) group rows into families
    families = families_from_columns(fam_id=fam_id, role=role,
                                     lower=lower, upper=upper)

    # 4) estimate the proband genetic liability, two ways. This toy uses one
    # coherent logistic age curve; full LT-FH++ requires population CIPs
    # stratified by age, sex and birth cohort.
    gibbs = estimate_liability(families, h2=H2, method="gibbs",
                               out=("genetic",), seed=0)
    pa = estimate_liability(families, h2=H2, method="pearson-aitken",
                            out=("genetic",))

    score = pa.est["genetic"]          # <- the phenotype you would use in a GWAS

    print(f"families                 : {len(families)}")
    print(f"Gibbs vs PA agreement    : "
          f"{np.corrcoef(gibbs.est['genetic'], score)[0, 1]:.4f}")
    print(f"corr(score, case/control): "
          f"{np.corrcoef(score, status[role == 'o'].astype(float))[0, 1]:.3f}")
    print(f"corr(score, true g)      : {np.corrcoef(score, true_g)[0, 1]:.3f}  "
          f"(vs case/control {np.corrcoef(status[role == 'o'].astype(float), true_g)[0, 1]:.3f})")

    # 5) example GWAS on standardized genotypes joined/aligned to `pa.pids`:
    #    y = (score - score.mean()) / score.std()
    #    chi2_j = n * corr(genotype_j, y) ** 2
    print("\nUse `pa.est['genetic']` joined to genotype rows by `pa.pids` as the GWAS phenotype.")


if __name__ == "__main__":
    main()
